version: "3"

services:

  mysql:
    image: mysql:8.0
    container_name: rifame-mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "rifame-api"
      MYSQL_USER: "name"
      MYSQL_PASSWORD: "password"
    volumes:
      - ./resources/migration:/docker-entrypoint-initdb.d/:ro
    ports:
      - "3306:3306"

  app:
    container_name: rifame-app
    build: ./
    dns:
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - '8080:8080'
    volumes:
      - ./:/app
    depends_on:
      - mysql